apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcpo-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcpo-backend
  template:
    metadata:
      labels:
        app: fcpo-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/areppzubaidi/fcpo-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: fcpo-postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: fcpo-postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fcpo-postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: fcpo-postgres-secret
              key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: fcpo-backend
  namespace: default
spec:
  selector:
    app: fcpo-backend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
