apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - postgres/01-pvc.yaml
  - postgres/02-secret.yaml
  - postgres/03-deployment.yaml
  - postgres/04-service.yaml
  - backend-deployment.yaml
