apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcpo-postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcpo-postgres
  template:
    metadata:
      labels:
        app: fcpo-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: fcpo-postgres-secret
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: fcpo-postgres-pvc
